### ISSUE TITLE
harmozining use of Dphase or Calphase

### ISSUE THREAD

**Issue by soerenthomsen** [OceanGlidersCommunity/Oxygen_SOP#143]
@s-pearce raised this important point: 

"In section 4.4, there is a note to always record DPhase, which is calphase. In the previous introduction section though it is referred to as calphase and P_c. As best I can tell, the reference to the note about DPhase is referring to Argo processing terminology specifically for calphase from a 3830 Aanderaa optode. Although I think term DPhase is relatively well known, it would be good to use consistent and clear terminology.

Reference for Argo Processing for the DPhase term:
Thierry V., H. Bittig, D. Gilbert, T. Kobayashi, K. Sato, C. Schmid, 2021: Processing Argo
OXYGEN data at the DAC level, v2.3.2, http://dx.doi.org/10.13155/39795"

**Comment by tomhull** [comment]
Yes so this is a change in terminology used by Aanderaa between optode version.
For the 383x, `DPhase` = calibrated phase
for the 4330 and onward `Calphase` = calibrated phase and `TCPhase` is temperature compensated phase.
For most optodes `TCPhase` is the same as `CalPhase` because the coefficients are set to 0 and 1. But I'm told there are some out there.

I think for the SOP, we should use the more recent name `CalPhase` and make a note that it is called `DPhase` on the 383x. Alternatively we could say "calibrated phase" whenever we refer to it?.

**Comment by soerenthomsen** [comment]
I think this is done right? @tomhull feel free to close when you agree.
