### ISSUE TITLE
which firmware allowed first SVU/Multipoint-calibration

### ISSUE THREAD

**Issue by soerenthomsen** [OceanGlidersCommunity/Oxygen_SOP#145]
@s-pearce

"Also, I believe it was framework 3 that first allowed the SVU/Multipoint-calibration, and firmware less than 3.x.x only used the Mk2 equation."

**Comment by s-pearce** [comment]
> Yep, the SVU equation is an option only on 4xxx series, which is since 2012 and only on those with serial numbers > #1000, firmware versions 4.4.8 or higher are needed.

@tomhull Although the serial numbers > #1000 bit is written in the manuals, that is only true for the 4330 form factor of the optode.  The 4831 form factor (same internal parts) has most serial numbers less than 1000 but are firmware versions higher than 4.4.8.  The 4831 SVU optodes I have range from serial numbers 100 to 800 and the newest were purchased just this year.  So I might leave that bit about the serial numbers out of any informational texts because it is partially incorrect, or provide a comment correcting it.

**Comment by tomhull** [comment]
@s-pearce that's a very good point! I'll amend the text.
