### ISSUE TITLE
how long sensor wet before deployment (8h or 24 h ...), consistent recommendation

### ISSUE THREAD

**Issue by soerenthomsen** [OceanGlidersCommunity/Oxygen_SOP#201]
### Discussed in https://github.com/OceanGlidersCommunity/Oxygen_SOP/discussions/193

<div type='discussions-op-text'>

<sup>Originally posted by **isgiddy** November 15, 2021</sup>
For each temperature run should we leave all materials, reagents and sensors in the lab/workshop/room overnight (or as recommended for 8 hours).

When time is limited, is it ok to begin calibration when the sensor equilibrates (if this occurs in a time period shorter than 8 hours)?

@patricialg @tomhull @hahn-johannes </div>

**Comment by soerenthomsen** [comment]
While preparing the cheat sheet I realised that in section 4.1. Storage and cleaning it is written `The sensor then needs to be placed in water to hydrate at least 24 h prior to starting field measurements again.`

Somewhere else we wrote 8 h. 

This is confusing and we need to align. Any citable literature on this? What is the minimum time?

@isgiddy might be interested.

**Comment by gkrahmann** [comment]
I can't say anything to that. For that I always follow instructions of colleagues...

It is important mostly when you have comparison/calibration CTD casts nearby. 
Otherwise you might just have a few hours of degraded oxygen data. For our gliders 
we slowly increase the dive depths after deployment so that the first dives are of little scientific use anyway.

Are there numbers for the errors by a dry foil ? How do they compared to overall accuracies ?

**Comment by patricialg** [comment]
For Aanderaa optodes, they recommend : 
_NOTE! To obtain the highest accuracy the sensor(s) to be calibrated should be submerged into water at least 24-48 hours prior to the calibration. If a sensor is allowed to dry out this could lead to a bias in the readings of up to 2 %. This effect disappears when the sensor is submerged into the water._
I used to leave them 8h or overnight and it was OK. Any suggestion? 
@soerenthomsen was mentioning to at least have the sensor covered with the wet sponge for 24h min (because if the sensor in mounted in the glider is more difficult to have them sumerged in water).  But we should clarify that when doing 0/100 calibration we need  to leave the sensors in water for 24-48h as the manufacturer recommends?

**Comment by hahn-johannes** [comment]
I also had in mind, that 24h are recommended for submerging the optodes in water before calibration. However, we often were limited in time on board before the upcoming deployment, which reduced the time for a wet preparation of the optodes to a couple of hours. For different calibration steps (0/100% in cold water --> 0/100% in warm water --> insitu calibration at CTD), we used wet tissues to keep the sensing foils wet.
We did not see any obvious systematic error, but also did not check this in detail.

**Comment by tomhull** [comment]
I think 24 hours is plenty and a good recomentation.
The rubber lens cover for the 4330 and 4831 series optodes has room for a small piece of absorbant material which can be used prior to deployment. I'm not sure if that cover fits when mounted to a slocum however @patricialg maybe you can find out?

**Comment by patricialg** [comment]
OK, I'll ask around MARS at NOC

**Comment by soerenthomsen** [comment]
Ok! So should we recommend 24 h following also the manufactures recommendation? Plus referring to the option to keep the optodes wet with some absorbent material in case a bath is not possible.

**Comment by soerenthomsen** [comment]
@patricialg do you feel this is ready to be implemented?

**Comment by patricialg** [comment]
Not too much, I have only had a chat with the ALR guys, they used SBE43 and they follow instructions from manufacturer (they keep it with MQ water). I think that 24h would be the best recomendation.

**Comment by soerenthomsen** [comment]
Agree

**Comment by soerenthomsen** [comment]
I made a PR #217 to implement this discussion.
