### ISSUE TITLE
"Used by" shield

### ISSUE THREAD

**Issue by soerenthomsen** [OceanGlidersCommunity/Oxygen_SOP#239]
I saw that for some software packages you can see who "uses them". 

Is that possible to add to this SOP? i.e. @callumrollo uses them for VOTO I think? And SouthAfrica? @isgiddy 

This would help to show how far we are in harmonising methods etc.

**Comment by callumrollo** [comment]
Hi Soeren, from what I've gathered, the "used by" functionality comes from the [dependency graph](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-the-dependency-graph). Looking at [cmcrameri](https://github.com/callumrollo/cmcrameri), a Python package I maintain, I see that the "used by" projects are Python projects that have cmcrameri in their `requirements.txt` files like [this one](https://github.com/Blueblue4/Object-Detection-Confidence-Bias/blob/main/requirements.txt).

As the SOPs are documents, rather than code dependencies, I don't think this feature will work :/

**Comment by soerenthomsen** [comment]
Ok! Thanks for checking! So we need to think about another way to list who is using this SOP.
