### ISSUE TITLE
Should we always build the html and pdf automatically to ensure errors are identified directly?

### ISSUE THREAD

**Issue by soerenthomsen** [OceanGlidersCommunity/Oxygen_SOP#5]
By adding a section to oxygen.md, I just had some issues as I copied over from formatted text so the pdf could not be build. Greek letters like mumol where the issue. For now I just write "mu" and the pdf is build. 

I think it is saver to let the two actions run each time something was added to oxygen.md to ensure it is easier to find the issue. @tomhull

**Comment by tomhull** [comment]
The problem is the action that builds the pdf also performs a commit, you'd
get in a commit->build loop.
Later I could make it so it runs before we make a release, then we can
check for any problems.

to get mu to render you'd do \mu, it won't look right in github, but it
will render correctly through pandoc
